from sequencer.devices.yesr_digital_board.device import YeSrDigitalBoard
from sequencer.devices.yesr_digital_board.channel import YeSrDigitalChannel

class WXYZ(YeSrDigitalBoard):
    autostart = True
    conductor_servername = 'conductor'
    ok_servername = 'yesr9_ok'
    ok_interface = '184000NUZ'

    is_master = False

#    channels = [
#        YeSrDigitalChannel(loc=['A', 0], name='3D MOT AOM', mode='auto', manual_output=False, invert=True),
#        YeSrDigitalChannel(loc=['A', 1], name='3D MOT Shutter', mode='auto', manual_output=False, invert=False),
#        YeSrDigitalChannel(loc=['A', 2], name='HR Abs. AOM', mode='auto', manual_output=False, invert=True),
#        YeSrDigitalChannel(loc=['A', 3], name='HR Abs. Shutter', mode='auto', manual_output=False, invert=False),
#        YeSrDigitalChannel(loc=['A', 4], name='LR Abs. AOM', mode='auto', manual_output=False, invert=True),
#        YeSrDigitalChannel(loc=['A', 5], name='LR H Abs. Shutter', mode='auto', manual_output=False, invert=False),
#        YeSrDigitalChannel(loc=['A', 6], name='LR V Abs. Shutter', mode='auto', manual_output=False, invert=False),
#        YeSrDigitalChannel(loc=['A', 7], name='2D MOT Shutter', mode='auto', manual_output=False, invert=True),
#        YeSrDigitalChannel(loc=['A', 8], name='Zeeman Shutter', mode='auto', manual_output=False, invert=False),
#        YeSrDigitalChannel(loc=['A', 9], name='AH Enable', mode='auto', manual_output=False, invert=False),
#        YeSrDigitalChannel(loc=['A', 10], name='AH Bottom Enable', mode='auto', manual_output=False, invert=False),
#        YeSrDigitalChannel(loc=['A', 11], name='V Camera Trig.', mode='auto', manual_output=False, invert=False),
#        YeSrDigitalChannel(loc=['A', 12], name='H Camera Trig.', mode='auto', manual_output=False, invert=False),
#        YeSrDigitalChannel(loc=['A', 13], name='LR V Camera Trig.', mode='auto', manual_output=False, invert=False),
#        YeSrDigitalChannel(loc=['A', 14], name='TTLA14', mode='auto', manual_output=False, invert=False),
#        YeSrDigitalChannel(loc=['A', 15], name='Gage Trig.', mode='auto', manual_output=False, invert=True),
#        
#        YeSrDigitalChannel(loc=['B', 0], name='Clock Detune', mode='auto', manual_output=False, invert=False),
#        YeSrDigitalChannel(loc=['B', 1], name='Clock Center/Sweep', mode='auto', manual_output=False, invert=False),
#        YeSrDigitalChannel(loc=['B', 2], name='Beta Phase', mode='auto', manual_output=False, invert=False),
#        YeSrDigitalChannel(loc=['B', 3], name='Spin Pol. LC Wave', mode='auto', manual_output=False, invert=False),
#        YeSrDigitalChannel(loc=['B', 4], name='HODT AOM', mode='auto', manual_output=False, invert=False),
#        YeSrDigitalChannel(loc=['B', 5], name='VODT AOM', mode='auto', manual_output=False, invert=False),
#        YeSrDigitalChannel(loc=['B', 6], name='HODT Shutter', mode='auto', manual_output=False, invert=False),
#        YeSrDigitalChannel(loc=['B', 7], name='VODT Shutter', mode='auto', manual_output=False, invert=False),
#        YeSrDigitalChannel(loc=['B', 8], name='MOT V Shutter', mode='auto', manual_output=False, invert=False),
#        YeSrDigitalChannel(loc=['B', 9], name='813 H1 AOM', mode='auto', manual_output=False, invert=False),
#        YeSrDigitalChannel(loc=['B', 10], name='813 H2 AOM', mode='auto', manual_output=False, invert=False),
#        YeSrDigitalChannel(loc=['B', 11], name='813 V AOM', mode='auto', manual_output=False, invert=False),
#        YeSrDigitalChannel(loc=['B', 12], name='M2 Shutter', mode='auto', manual_output=False, invert=False),
#        YeSrDigitalChannel(loc=['B', 13], name='813 H1 Shutter', mode='auto', manual_output=False, invert=False),
#        YeSrDigitalChannel(loc=['B', 14], name='813 H2 Shutter', mode='auto', manual_output=False, invert=False),
#        YeSrDigitalChannel(loc=['B', 15], name='813 V Shutter', mode='auto', manual_output=False, invert=False),
#        
#        YeSrDigitalChannel(loc=['C', 0], name='Broken!C00', mode='auto', manual_output=False, invert=False),
#        YeSrDigitalChannel(loc=['C', 1], name='RM Gain Switch', mode='auto', manual_output=False, invert=False),
#        YeSrDigitalChannel(loc=['C', 2], name='STIRAP P Switch', mode='auto', manual_output=False, invert=True),
#        YeSrDigitalChannel(loc=['C', 3], name='STIRAP P Trigger', mode='auto', manual_output=False, invert=False),
#        YeSrDigitalChannel(loc=['C', 4], name='STIRAP S Shutter', mode='auto', manual_output=False, invert=False),
#        YeSrDigitalChannel(loc=['C', 5], name='STIRAP S Switch', mode='auto', manual_output=False, invert=False),
#        YeSrDigitalChannel(loc=['C', 6], name='STIRAP S Trigger', mode='auto', manual_output=False, invert=False),
#        YeSrDigitalChannel(loc=['C', 7], name='V Clock Switch', mode='manual', manual_output=True, invert=True),
#        YeSrDigitalChannel(loc=['C', 8], name='Clock Servo Enable', mode='manual', manual_output=True, invert=False),
#        YeSrDigitalChannel(loc=['C', 9], name='TTLC09', mode='auto', manual_output=False, invert=False),
#        YeSrDigitalChannel(loc=['C', 10], name='TTLC10', mode='auto', manual_output=False, invert=False),
#        YeSrDigitalChannel(loc=['C', 11], name='TTLC11', mode='auto', manual_output=False, invert=False),
#        YeSrDigitalChannel(loc=['C', 12], name='Troubleshoot', mode='auto', manual_output=False, invert=False),
#        YeSrDigitalChannel(loc=['C', 13], name='SrQ Comb Shutter', mode='auto', manual_output=False, invert=False),
#        YeSrDigitalChannel(loc=['C', 14], name='Sr1 Comb Shutter', mode='auto', manual_output=False, invert=False),
#        YeSrDigitalChannel(loc=['C', 15], name='ODT Servo Enable', mode='manual', manual_output=True, invert=False),
#        
#        YeSrDigitalChannel(loc=['D', 0], name='Alpha AOM', mode='auto', manual_output=False, invert=False),
#        YeSrDigitalChannel(loc=['D', 1], name='Alpha Shutter', mode='auto', manual_output=False, invert=True),
#        YeSrDigitalChannel(loc=['D', 2], name='Beta AOM', mode='auto', manual_output=False, invert=False),
#        YeSrDigitalChannel(loc=['D', 3], name='Beta Shutter', mode='auto', manual_output=False, invert=True),
#        YeSrDigitalChannel(loc=['D', 4], name='Spin Pol. AOM', mode='auto', manual_output=False, invert=True),
#        YeSrDigitalChannel(loc=['D', 5], name='Spin Pol. Shutter', mode='auto', manual_output=False, invert=True),
#        YeSrDigitalChannel(loc=['D', 6], name='679 AOM', mode='auto', manual_output=False, invert=False),
#        YeSrDigitalChannel(loc=['D', 7], name='707 AOM', mode='auto', manual_output=False, invert=False),
#        YeSrDigitalChannel(loc=['D', 8], name='Repump Shutter', mode='auto', manual_output=False, invert=True),
#        YeSrDigitalChannel(loc=['D', 9], name='RM FM Trigger', mode='auto', manual_output=False, invert=False),
#        YeSrDigitalChannel(loc=['D', 10], name='TTLD10', mode='auto', manual_output=False, invert=False),
#        YeSrDigitalChannel(loc=['D', 11], name='TTLD11', mode='auto', manual_output=False, invert=False),
#        YeSrDigitalChannel(loc=['D', 12], name='TTLD12', mode='auto', manual_output=False, invert=False),
#        YeSrDigitalChannel(loc=['D', 13], name='TTLD13', mode='auto', manual_output=False, invert=False),
#        YeSrDigitalChannel(loc=['D', 14], name='AOSense Heater Enable', mode='manual', manual_output=True, invert=False),
#        YeSrDigitalChannel(loc=['D', 15], name='Trigger', mode='auto', manual_output=False, invert=True),
#        ]
    channels = [
        YeSrDigitalChannel(loc=['W', 0], name='W - 3D MOT AOM', mode='auto', manual_output=False, invert=True),
        YeSrDigitalChannel(loc=['W', 1], name='W - 3D MOT Shutter', mode='auto', manual_output=False, invert=False),
        YeSrDigitalChannel(loc=['W', 2], name='W - HR Abs. AOM', mode='auto', manual_output=False, invert=True),
        YeSrDigitalChannel(loc=['W', 3], name='W - HR Abs. Shutter', mode='auto', manual_output=False, invert=False),
        YeSrDigitalChannel(loc=['W', 4], name='W - LR Abs. AOM', mode='auto', manual_output=False, invert=True),
        YeSrDigitalChannel(loc=['W', 5], name='W - LR H Abs. Shutter', mode='auto', manual_output=False, invert=False),
        YeSrDigitalChannel(loc=['W', 6], name='W - LR V Abs. Shutter', mode='auto', manual_output=False, invert=False),
        YeSrDigitalChannel(loc=['W', 7], name='W - 2D MOT Shutter', mode='auto', manual_output=False, invert=True),
        YeSrDigitalChannel(loc=['W', 8], name='W - Zeeman Shutter', mode='auto', manual_output=False, invert=False),
        YeSrDigitalChannel(loc=['W', 9], name='W - AH Enable', mode='auto', manual_output=False, invert=False),
        YeSrDigitalChannel(loc=['W', 10], name='W - AH Bottom Enable', mode='auto', manual_output=False, invert=False),
        YeSrDigitalChannel(loc=['W', 11], name='W - V Camera Trig.', mode='auto', manual_output=False, invert=False),
        YeSrDigitalChannel(loc=['W', 12], name='W - H Camera Trig.', mode='auto', manual_output=False, invert=False),
        YeSrDigitalChannel(loc=['W', 13], name='W - LR V Camera Trig.', mode='auto', manual_output=False, invert=False),
        YeSrDigitalChannel(loc=['W', 14], name='W - TTLA14', mode='auto', manual_output=False, invert=False),
        YeSrDigitalChannel(loc=['W', 15], name='W - Gage Trig.', mode='auto', manual_output=False, invert=True),
        
        YeSrDigitalChannel(loc=['X', 0], name='X - Clock Detune', mode='auto', manual_output=False, invert=False),
        YeSrDigitalChannel(loc=['X', 1], name='X - Clock Center/Sweep', mode='auto', manual_output=False, invert=False),
        YeSrDigitalChannel(loc=['X', 2], name='X - Beta FM Switch', mode='auto', manual_output=False, invert=False),
        YeSrDigitalChannel(loc=['X', 3], name='X - Spin Pol. LC Wave', mode='auto', manual_output=False, invert=False),
        YeSrDigitalChannel(loc=['X', 4], name='X - HODT AOM', mode='auto', manual_output=False, invert=False),
        YeSrDigitalChannel(loc=['X', 5], name='X - VODT AOM', mode='auto', manual_output=False, invert=False),
        YeSrDigitalChannel(loc=['X', 6], name='X - HODT Shutter', mode='auto', manual_output=False, invert=False),
        YeSrDigitalChannel(loc=['X', 7], name='X - VODT Shutter', mode='auto', manual_output=False, invert=False),
        YeSrDigitalChannel(loc=['X', 8], name='X - MOT V Shutter', mode='auto', manual_output=False, invert=False),
        YeSrDigitalChannel(loc=['X', 9], name='X - 813 H1 AOM', mode='auto', manual_output=False, invert=False),
        YeSrDigitalChannel(loc=['X', 10], name='X - 813 H2 AOM', mode='auto', manual_output=False, invert=False),
        YeSrDigitalChannel(loc=['X', 11], name='X - 813 V AOM', mode='auto', manual_output=False, invert=False),
        YeSrDigitalChannel(loc=['X', 12], name='X - M2 Shutter', mode='manual', manual_output=True, invert=False),
        YeSrDigitalChannel(loc=['X', 13], name='X - 813 H1 Shutter', mode='auto', manual_output=False, invert=False),
        YeSrDigitalChannel(loc=['X', 14], name='X - 813 H2 Shutter', mode='auto', manual_output=False, invert=False),
        YeSrDigitalChannel(loc=['X', 15], name='X - 813 V Shutter', mode='auto', manual_output=False, invert=False),
        
        YeSrDigitalChannel(loc=['Y', 0], name='Y - Broken!C00', mode='auto', manual_output=False, invert=False),
        YeSrDigitalChannel(loc=['Y', 1], name='Y - RM Gain Switch', mode='auto', manual_output=False, invert=False),
        YeSrDigitalChannel(loc=['Y', 2], name='Y - LR AOM Sweep', mode='auto', manual_output=False, invert=True),
        YeSrDigitalChannel(loc=['Y', 3], name='Y - LR Demod Sweep', mode='auto', manual_output=False, invert=False),
        YeSrDigitalChannel(loc=['Y', 4], name='Y - LR/HR [hi/lo]', mode='auto', manual_output=False, invert=False),
        YeSrDigitalChannel(loc=['Y', 5], name='Y - HR AOM Sweep', mode='auto', manual_output=False, invert=False),
        YeSrDigitalChannel(loc=['Y', 6], name='Y - HR Demod Sweep', mode='auto', manual_output=False, invert=False),
        YeSrDigitalChannel(loc=['Y', 7], name='Y - V Clock Switch', mode='manual', manual_output=True, invert=True),
        YeSrDigitalChannel(loc=['Y', 8], name='Y - Clock Servo Enable', mode='manual', manual_output=True, invert=False),
        YeSrDigitalChannel(loc=['Y', 9], name='Y - RM Table Shutters', mode='manual', manual_output=True, invert=False),
        YeSrDigitalChannel(loc=['Y', 10], name='Y - RM Horizontal Shutter', mode='auto', manual_output=False, invert=False),
        YeSrDigitalChannel(loc=['Y', 11], name='Y - Transp. AOM', mode='auto', manual_output=False, invert=False),
        YeSrDigitalChannel(loc=['Y', 12], name='Y - Troubleshoot', mode='auto', manual_output=False, invert=False),
        YeSrDigitalChannel(loc=['Y', 13], name='Y - Alpha FM Switch', mode='auto', manual_output=False, invert=False),
        YeSrDigitalChannel(loc=['Y', 14], name='Y - Transp. Shutter', mode='auto', manual_output=False, invert=False),
        YeSrDigitalChannel(loc=['Y', 15], name='Y - ODT Servo Enable', mode='manual', manual_output=True, invert=False),
        
        YeSrDigitalChannel(loc=['Z', 0], name='Z - Alpha AOM', mode='auto', manual_output=False, invert=False),
        YeSrDigitalChannel(loc=['Z', 1], name='Z - Alpha Shutter', mode='auto', manual_output=False, invert=True),
        YeSrDigitalChannel(loc=['Z', 2], name='Z - Beta AOM', mode='auto', manual_output=False, invert=False),
        YeSrDigitalChannel(loc=['Z', 3], name='Z - Beta Shutter', mode='auto', manual_output=False, invert=True),
        YeSrDigitalChannel(loc=['Z', 4], name='Z - Spin Pol. AOM', mode='auto', manual_output=False, invert=True),
        YeSrDigitalChannel(loc=['Z', 5], name='Z - Spin Pol. Shutter', mode='auto', manual_output=False, invert=True),
        YeSrDigitalChannel(loc=['Z', 6], name='Z - 679 AOM', mode='auto', manual_output=False, invert=False),
        YeSrDigitalChannel(loc=['Z', 7], name='Z - 707 AOM', mode='auto', manual_output=False, invert=False),
        YeSrDigitalChannel(loc=['Z', 8], name='Z - Repump Shutter', mode='auto', manual_output=False, invert=True),
        YeSrDigitalChannel(loc=['Z', 9], name='Z - RM FM Trigger', mode='auto', manual_output=False, invert=False),
        YeSrDigitalChannel(loc=['Z', 10], name='Z - TTLD10', mode='auto', manual_output=False, invert=False),
        YeSrDigitalChannel(loc=['Z', 11], name='Z - StepperMotor', mode='manual', manual_output=False, invert=False),
        YeSrDigitalChannel(loc=['Z', 12], name='Z - TTLD12', mode='manual', manual_output=True, invert=False),
        YeSrDigitalChannel(loc=['Z', 13], name='Z - TTLD13', mode='manual', manual_output=False, invert=False),
        YeSrDigitalChannel(loc=['Z', 14], name='Z - AOSense Heater Enable', mode='manual', manual_output=True, invert=False),
        YeSrDigitalChannel(loc=['Z', 15], name='Z - Trigger', mode='auto', manual_output=False, invert=False),
        ]
    
        
Device = WXYZ
